CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(50),
    EMAILID VARCHAR(50),
    PASSWORD VARCHAR(50),
    CREATED_AT DATE DEFAULT (datetime('now', 'localtime'))
);


-- CREATE TABLE IF NOT EXISTS MEDIA_MASTER (
-- ID INTEGER PRIMARY KEY AUTOINCREMENT,
-- NAME VARCHAR2(50),
-- MEDIA_TYPE VARCHAR(50),
-- PATH VARCHAR(500),
-- USED_AT VARCHAR(50)

-- );

-- CREATE TABLE SECTION_MASTER (
--     ID INTEGER PRIMARY KEY AUTOINCREMENT,
--     SECTION_NAME VARCHAR(100),
-- );

-- 1, HOME_TITLE, STRING, 1
-- 2, HOME_CLIENT_PHOTOS, .JPEG\.PNG, LIST

-- CREATE TABLE SECTION_CHILD(
--     ID INTEGER PRIMARY KEY AUTOINCREMENT,
--     SECTION_ID INTEGER,
--     DATA_TYPE VARCHAR(50), 

--     FOREIGN KEY (SECTION_ID) REFERENCES SECTION_MASTER(ID)


-- )



