export FLASK_ENV=development
export FLASK_APP=src
export JWT_ACCESS_TOKEN_EXPIRES=30
export JWT_REFRESH_TOKEN_EXPIRES=180
export JWT_REFRESH_TOKEN_RENEW_THRESHOLD=60
export HOSTNAME="0.0.0.0"
export PORT=80
export DEBUG=True

