export FLASK_ENV=development
export FLASK_APP=src
export JWT_ACCESS_TOKEN_EXPIRES=30
export JWT_REFRESH_TOKEN_EXPIRES=180
export JWT_REFRESH_TOKEN_RENEW_THRESHOLD=60
export HOSTNAME=127.0.0.1
export PORT=8000
